// ordre de clignotement de 10 LEDS.

int bernard = 4;
int regis = 5;
int francis = 6;
int gerard = 7;
int baguette = 8;
int bonjour = 9;
int toureiffel = 10;
int chocolatine = 11;
int painauchocolat = 12;
int cocorico = 13;

void setup()
{
  pinMode(bernard, OUTPUT);
  pinMode(regis, OUTPUT);
  pinMode(francis, OUTPUT);
  pinMode(gerard, OUTPUT);
  pinMode(baguette, OUTPUT);
  pinMode(bonjour, OUTPUT);
  pinMode(toureiffel, OUTPUT);
  pinMode(chocolatine, OUTPUT);
  pinMode(painauchocolat, OUTPUT);
  pinMode(cocorico, OUTPUT);
}

void loop()
{
  digitalWrite(bernard, HIGH);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, HIGH);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, HIGH);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, HIGH);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, HIGH);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, HIGH);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, HIGH);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, HIGH);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, HIGH);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, HIGH);
  delay(200);
  
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, HIGH);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, HIGH);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, HIGH);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, HIGH);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, HIGH);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, HIGH);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, LOW);
  digitalWrite(francis, HIGH);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, LOW);
  digitalWrite(regis, HIGH);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
  delay(200);
  digitalWrite(bernard, HIGH);
  digitalWrite(regis, LOW);
  digitalWrite(francis, LOW);
  digitalWrite(gerard, LOW);
  digitalWrite(baguette, LOW);
  digitalWrite(bonjour, LOW);
  digitalWrite(toureiffel, LOW);
  digitalWrite(chocolatine, LOW);
  digitalWrite(painauchocolat, LOW);
  digitalWrite(cocorico, LOW);
}
